#http://lobservateur.bf/
import requests
from datetime import date
from bs4 import BeautifulSoup
from connection import cnxn
today = date.today()

print('starting')

cursor = cnxn.cursor()
#r=requests.get('http://lobservateur.bf/') An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.
r=requests.get('https://www.theworldfolio.com/botswana')
soup = BeautifulSoup(r.content, "html.parser")

titles=[]
descr=[]
images=[]
url=[]

primary = soup.find("div", class_= "col listado") 
for x in primary.findAll("div", class_= "col-12 row"):
    title=x.find('h2').get_text()
    myurl=x.find('h2').find('a')['href']
    print("TITLE = " +title)
    print("URL = " +myurl)
    titles.append(title.lstrip())
    url.append(myurl.lstrip())

# # # print("...................................................")

for x in primary.findAll("div",class_="texto"):
    descr.append(x.get_text().lstrip())
    print("DESCRIPTION = " +x.get_text())

for x in primary.findAll('a'):
    if not(x.find('img') is None):
        t=x.find('img')['src']
        images.append(t)
        print("IMG = " +t)
for x in range(len(descr)):
    cursor.execute("insert into nc_news(tTitle,tDescription,tPhoto,country_Id,category_Id,createdDate,aURL) values(?,?,?,?,?,?,?)",titles[x],descr[x],images[x],4,1,today,url[x])
cnxn.commit()
